# PyTorch requirements:

* torch: Core Pytorch package that contains tensors and neural networks.
* torchvision: Image processing
* torchaudio: Audio related task


# Tensors is the core of PyTorch

Tensors are multi-dimensional arrays that PyTorch uses to store and manipulate data.
They are optimize for GPUs

In [6]:
import torch

# singular number (scalar)
scalar = torch.tensor(3.0)
print(scalar)

tensor(3.)


In [7]:
# A one-dimensional tensor (vector)
vector = torch.tensor([1,2,3])
print(vector)

tensor([1, 2, 3])


In [8]:
# A two-dimensional tensor (matrix)
matrix = ([[1,2], [3,4]])
print(matrix)

[[1, 2], [3, 4]]


In [10]:
# Random 3D tensor
tensor_3d = torch.rand(3,3,3)
print(tensor_3d)

tensor([[[0.4297, 0.7092, 0.4210],
         [0.2360, 0.6707, 0.1202],
         [0.3439, 0.0060, 0.7333]],

        [[0.4656, 0.3422, 0.2638],
         [0.5089, 0.1415, 0.1580],
         [0.4265, 0.5015, 0.0097]],

        [[0.7981, 0.5993, 0.2802],
         [0.9626, 0.0417, 0.2485],
         [0.3987, 0.5287, 0.4706]]])


# Basic tensor operations

In [11]:
a = torch.tensor([2.0, 3.0])
b = torch.tensor([4.0, 5.0])

In [12]:
print(a+b)

tensor([6., 8.])


In [13]:
print(a*b)

tensor([ 8., 15.])


In [ ]:
print(a @ b) # dot product for matrix multiplication

tensor(23.)


# Move to GPU for Speed

In [16]:
device  = torch.device("cuda" if torch.cuda.is_available() else "cpu")  
x = torch.rand(3,3).to(device)
print(x.device)

cpu


# Defining a Neural Network in Pytorch

In [18]:
import torch.nn as nn
import torch.optim as optim

# Defining a network
class SimpleNN(nn.Module):
    def __init__(self):
        super(SimpleNN, self).__init__()
        self.fc1 = nn.Linear(2,3)
        self.fc2 = nn.Linear(3,1)

    def forward(self, x):
        x = torch.relu(self.fc1(x)) # acivation function
        x = torch.sigmoid(self.fc2(x))
        return x
    
model = SimpleNN()


# Loss Function and Optimizer

Neural networks learn by minimizing a loss function using an optimizer

In [ ]:
criterion = nn.BCELoss() # Binary cross entropy loss function
optimizer = optim.Adam(model.parameters(), lr=0.01) # A popular optimizer that adjusts learning rates dynamically.

# Training Neural Network

In [21]:
# Example xor dataset
X = torch.tensor([[0,0], [0,1], [1,0], [1,1]], dtype=torch.float32)
Y = torch.tensor([[0], [1], [1], [0]], dtype=torch.float32) # XOR labels

for epoch in range(1000):
    optimizer.zero_grad() # Reset gradients to zero
    y_pred = model(X) # Forward pass(prediction)
    loss = criterion(y_pred, Y) # Compute loss
    loss.backward() # Backpropagation (Compute gradients)
    optimizer.step()

    if epoch % 100 == 0:
        print(f'Epoch {epoch}, Loss: {loss.item():.4f}')

        

Epoch 0, Loss: 0.7339
Epoch 100, Loss: 0.5524
Epoch 200, Loss: 0.2728
Epoch 300, Loss: 0.1235
Epoch 400, Loss: 0.0649
Epoch 500, Loss: 0.0394
Epoch 600, Loss: 0.0264
Epoch 700, Loss: 0.0190
Epoch 800, Loss: 0.0143
Epoch 900, Loss: 0.0112


# Evaluating the model

In [22]:
with torch.no_grad():
    y_test = model(X)
    print(y_test)

tensor([[0.0066],
        [0.9795],
        [0.9958],
        [0.0043]])


# Using DataLoader for Large Datasets

For large datasets, pytorch provides dataset and data loader to hanlde batching.

In [23]:
from torch.utils.data import Dataset, DataLoader

In [27]:
# Custom dataset class
class CustomDataset(Dataset):
    def __init__(self):
        self.data = torch.rand(100,2) # 100 samples, 2 features
        self.labels = torch.randint(0,2,(100,1), dtype=torch.float32)

    def __len__(self):
        return len(self.data)
    
    def __getitem__(self, idx):
        return self.data[idx], self.labels[idx]
    
dataset = CustomDataset()
dataloader = DataLoader(dataset, batch_size=10, shuffle=True)

for batch in dataloader:
    inputs, lables = batch
    print(inputs.shape)
    break # print only first batch

torch.Size([10, 2])


# What’s happening here?

* Dataset Class: Defines how to load data.
* DataLoader: Handles batch processing efficiently.
* Use Case: Essential when working with large datasets like images or text.

In [28]:
# Save Model
torch.save(model.state_dict(), "model.pth")

In [ ]:
# Load Model Saves a trained model so you can load it later without retraining.
model.load_state_dict(torch.load("model.pth"))

<All keys matched successfully>